In [12]:
# Create a vector
v <- c(5, 10, 15, 20, 25)
print(v)

#added one

[1]  5 10 15 20 25


In [13]:
m <- matrix(1:6, nrow=2, ncol=3) 
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [14]:
m[2, 3]

[1] 6

In [15]:
m[1, 2] <- 99
print(m)

     [,1] [,2] [,3]
[1,]    1   99    5
[2,]    2    4    6


In [16]:
#Create two small 2x2 matrices and multiply them:

a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 1, 3), nrow=2)

result <- a %*% b
print(result)

     [,1] [,2]
[1,]    2   10
[2,]    4   14
