In [1]:
data_matrix <- matrix(c(100, 0.8, 200, 1.2, 300, 1.7), nrow = 3, byrow = TRUE)
scaled <- scale(data_matrix)
print(scaled)

     [,1]        [,2]
[1,]   -1 -0.96098765
[2,]    0 -0.07392213
[3,]    1  1.03490978
attr(,"scaled:center")
[1] 200.000000   1.233333
attr(,"scaled:scale")
[1] 100.000000   0.450925


In [2]:
#Use %*% for matrix multiplication. For example:

transformation <- matrix(c(1, 0, 0, -1), nrow=2)
result <- scaled %*% transformation
#This transformation flips the sign of the second column (e.g., temperature) while keeping the first column unchanged.

In [3]:
#Practice with a small matrix:

m <- matrix(c(200, 1.5, 180, 1.3, 160, 1.1), nrow=3, byrow=TRUE)
scaled <- scale(m)
print(scaled)

# Flip the temperature column
flip <- matrix(c(1, 0, 0, -1), nrow=2)
result <- scaled %*% flip
print(result)

     [,1] [,2]
[1,]    1    1
[2,]    0    0
[3,]   -1   -1
attr(,"scaled:center")
[1] 180.0   1.3
attr(,"scaled:scale")
[1] 20.0  0.2
     [,1] [,2]
[1,]    1   -1
[2,]    0    0
[3,]   -1    1


In [4]:
# Create a 5x3 matrix: [CO2, Temp Anomaly, Deforestation Rate]
climate <- matrix(c(
  9.2, 1.1, 0.8,   # Country A
  6.5, 0.9, 1.2,   # Country B
  2.3, 0.7, 2.5,   # Country C
  3.8, 1.0, 1.5,   # Country D
  7.1, 1.2, 0.9    # Country E
), nrow=5, byrow=TRUE)

colnames(climate) <- c("CO2", "Temp", "Deforestation")
rownames(climate) <- c("A", "B", "C", "D", "E")

print(climate)

  CO2 Temp Deforestation
A 9.2  1.1           0.8
B 6.5  0.9           1.2
C 2.3  0.7           2.5
D 3.8  1.0           1.5
E 7.1  1.2           0.9


In [5]:
scaled_climate <- scale(climate)
print(scaled_climate)

         CO2       Temp Deforestation
A  1.2490573  0.6238503    -0.8487300
B  0.2629594 -0.4159002    -0.2633990
C -1.2709706 -1.4556507     1.6389269
D -0.7231384  0.1039750     0.1755993
E  0.4820923  1.1437255    -0.7023972
attr(,"scaled:center")
          CO2          Temp Deforestation 
         5.78          0.98          1.38 
attr(,"scaled:scale")
          CO2          Temp Deforestation 
    2.7380650     0.1923538     0.6833740 


In [6]:
#Let’s invert the deforestation rate so higher values reflect lower impact (for comparison purposes).

# Transformation matrix: keep CO2 and Temp, invert Deforestation
flip <- matrix(c(1, 0, 0,
                 0, 1, 0,
                 0, 0, -1), nrow=3)

transformed <- scaled_climate %*% flip
print(transformed)
#🧠 Question: Why might inverting some metrics make sense when analyzing sustainability data?

        [,1]       [,2]       [,3]
A  1.2490573  0.6238503  0.8487300
B  0.2629594 -0.4159002  0.2633990
C -1.2709706 -1.4556507 -1.6389269
D -0.7231384  0.1039750 -0.1755993
E  0.4820923  1.1437255  0.7023972


In [7]:
#Sometimes we need to flip rows and columns to match other analysis tools.

transposed <- t(transformed)
print(transposed)
#This transposed matrix has variables as rows and countries as columns — useful when plotting heatmaps.

             A          B         C          D         E
[1,] 1.2490573  0.2629594 -1.270971 -0.7231384 0.4820923
[2,] 0.6238503 -0.4159002 -1.455651  0.1039750 1.1437255
[3,] 0.8487300  0.2633990 -1.638927 -0.1755993 0.7023972


In [8]:
#Try this:

#Add a sixth country to the matrix.
#Change the transformation matrix to weight CO₂ more heavily (e.g., multiply it by 2).
#Transpose again and compare the new values.
# Example: double the CO2 contribution
weight <- matrix(c(2, 0, 0,
                   0, 1, 0,
                   0, 0, -1), nrow=3)

adjusted <- scaled_climate %*% weight
print(adjusted)

        [,1]       [,2]       [,3]
A  2.4981145  0.6238503  0.8487300
B  0.5259188 -0.4159002  0.2633990
C -2.5419411 -1.4556507 -1.6389269
D -1.4462768  0.1039750 -0.1755993
E  0.9641846  1.1437255  0.7023972


In [9]:
cor_matrix <- cor(scaled_climate)
print(cor_matrix)

                     CO2       Temp Deforestation
CO2            1.0000000  0.7490355    -0.9195016
Temp           0.7490355  1.0000000    -0.8976824
Deforestation -0.9195016 -0.8976824     1.0000000
